### ISSUE TITLE
Seems to be broken now

### ISSUE THREAD

**Issue by sector-f** [onespaceman/polyfy#13]
No matter what I run, I'm getting `convert: geometry does not contain image `none' @ warning/attribute.c/GetImageBoundingBox/247.`

**Comment by onespaceman** [comment]
Could I get the output of

> bash -x [your polyfy command]

**Comment by onespaceman** [comment]
nevermind. Fixed it. I had changed the matte geometry to be $length x $length but forgot to change the variable from $length x $height.
